### ISSUE TITLE
External site only branch

### ISSUE THREAD

**Issue by rwagner00** [palantirnet/butler#2]
We need a branch which only supports proxy for an external site for its compiling, so Drupal (and other) sites without a prototype can benefit from Butler.

**Comment by labyrwa** [comment]
@rwagner00 can you confirm the use case for this? My interpretation is that this would be a Drupal (lets just start there for simplicity sake) site that needs front end work but does not have a prototype.

**Comment by rwagner00** [comment]
The use case here is for Drupal only and for static sites that aren't using generators.
