### ISSUE TITLE
Config overrides in conf/butler.default.js not being used

### ISSUE THREAD

**Issue by gleroux02** [palantirnet/butler#28]
The configuration variables custom to the project that are stored in the conf/butler.default.js are not being used. If you run console.log(defaults) in the gulpfile after trying to pull in the custom variables you will receive the following output even with a git remote repository being set:
```
{ scss:
   [ '../../styleguide/source/code/sass/*.scss',
     '../../styleguide/source/code/sass/**/*.scss' ],
  css: '../../styleguide/source/code/css/',
  sculpin: '../../styleguide/',
  output_dev: '../../styleguide/output_dev',
  output_prod: '../../styleguide/output_prod/**/*',
  sculpin_run: '../../vendor/bin/sculpin',
  autoprefixer: { browsers: [ 'last 2 versions', '> 5%' ] },
  stylelint: { configFile: 'config/linters/stylelint.config.json' },
  deploy: { remoteUrl: undefined } }
```

I have a solution for this that I will link a PR to: https://github.com/palantirnet/butler/pull/29

**Comment by labbydev** [comment]
@gleroux02 This is resolved now that #29 is done.
