### ISSUE TITLE
Update master branch README

### ISSUE THREAD

**Issue by labbydev** [palantirnet/butler#5]
Currently the README for master doesn't address the "Umm... there's no code here, how do I work with this" aspect, which I think should be addressed first thing in the README.

**Comment by labyrwa** [comment]
@patrickfweston I need someone who doesn't know much about the project.

I would like you to put yourself in the shoes of a developer looking for tools who stumbled across this link https://github.com/palantirnet/butler and is trying to test out Butler for the first time. 

Read through the documentation, let me know where you have questions, comments and concerns. 

If you're feeling so enquired I encourage you to take it a step further and figure out if you could pick this up and use it without assistance or prior knowledge of the framework. 

(Although I'm aware that you have great debug skills, try not to use them. If you feel the need to debug things flag those as issues either with the framework or the documentation).

**Comment by patrickfweston** [comment]
@labyrwa Awesome. I will put myself in the shoes of a curious developer, and I will be as quizzical as possible. Also, it'd be pretty awesome if we made a splash page for this tool once we get it going.

**Comment by labyrwa** [comment]
See these are the kinds of great comments I'm looking for

**Comment by patrickfweston** [comment]
@labyrwa I couldn't get it to install correctly, including trying to debug it to get it to work. I've written up a doc on what's happening through comments on the Readme and attached some screenshots

![image](https://cloud.githubusercontent.com/assets/2760383/9922750/af0f3c9c-5cb1-11e5-8558-ce9954356f6a.png)

<img width="823" alt="screen shot 2015-09-16 at 7 58 20 pm" src="https://cloud.githubusercontent.com/assets/2760383/9922751/b267e826-5cb1-11e5-9de1-c7e3585b3161.png">

https://docs.google.com/a/palantir.net/document/d/1SLKgDxiYpzNaLbvvMdgZBfQSzm13xS0GPzWiE7GcvAI/edit?usp=sharing
