### ISSUE TITLE
Delete *.info is breaking things

### ISSUE THREAD

**Issue by labbydev** [palantirnet/butler#8]
```
npm WARN cannot run in wd fed-automation@1.0.0 find node_modules/ -name '*.info' -type f -delete (wd=/Users/LaurenByrwa/Sites/butler)
```

**Comment by labyrwa** [comment]
If Butler lives in the project root and not the Drupal root then this throws a lot of errors and since it is in the `package.json` as a `postinstall` it won't let you `npm install` at all either.

**Comment by labbydev** [comment]
Even without this the static version of the jekyll side of Butler will not work, throws an error: `Task browser-sync-prototype-only dependency undefined is not a string` The sculpin side tries to work. But fails because of undefined Promise from gulp-autoprefixer.
